### ISSUE TITLE
How to remove path prefix?

### ISSUE THREAD

**Issue by miloskroulik** [jerryjappinen/Servant#1]
Is there any way to remove path prefix (by default "site")? I found a way to change it, but I wasn't able to remove it entirely.

**Comment by jerryjappinen** [comment]
Currently there is not. The first part of the URL always specifies an action, and the site action is what outputs a web page for the user. You can change it, like you said, but there needs to be something there.

There's a small chance that this is changed in the future, but this is how it works now. The URLs work fairly intuitively like this and many problems that arise with working without the prefix are avoided. Servant also includes adequate tools to composing and manipulating URLs reliably, and these will be improved still in the near future.
